//go:build wireinject
//+build wireinject
package app

import (
	"github.com/google/wire"
	"github.com/kyusscaesar/go-web-app/monitoringapi"
	"github.com/kyusscaesar/go-web-app/userapi"
)

// Function GetApplication returns a new instance of the application. It is auto-generated by `wire`.
func GetApplication() Application {
	wire.Build(monitoringapi.MonitoringApiSet, userapi.UserApiSet, AppSet)
	return Application{}
}
