// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/kyusscaesar/go-web-app/userapi"
)

// Injectors from app.injector.go:

func GetApplication() Application {
	engine := ProvideEngine()
	userController := userapi.ProvideUserController()
	application := ProvideApplication(engine, userController)
	return application
}
