// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/kyusscaesar/go-web-app/monitoringapi"
	"github.com/kyusscaesar/go-web-app/userapi"
)

// Injectors from app.wire-injector.go:

// Function GetApplication returns a new instance of the application. It is auto-generated by `wire`.
func GetApplication() Application {
	engine := ProvideEngine()
	monitoringController := monitoringapi.ProvideMonitoringController()
	userController := userapi.ProvideUserController()
	application := ProvideApplication(engine, monitoringController, userController)
	return application
}
