// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kyusscaesar/go-web-app/app"
	"github.com/kyusscaesar/go-web-app/userapi"
)

// Injectors from wire.go:

func GetApplication() app.Application {
	engine := app.ProvideEngine()
	userController := userapi.ProvideUserController()
	application := app.ProvideApplication(engine, userController)
	return application
}
